name: Build And Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}

      - name: Cache chaizi-jt.txt file
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: ./chaizi-jt.txt
          key: ${{ runner.os }}-chaizi-jt-${{ hashFiles('./chaizi-jt.txt') }}

      - name: Run Makefile
        run: make

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./build/chaizi.dict.yaml
            ./build/chaizi.schema.yaml
